def lt(x y)
    if x < y then
        1
    else
        0
    end;

def le(x y)
    if x <= y then
        1
    else
        0
    end;

def gt(x y)
    if x > y then
        1
    else
        0
    end;

def ge(x y)
    if x >= y then
        1
    else
        0
    end;

def eq(x y)
    if x == y then
        1
    else
        0
    end;

def ne(x y)
    if x != y then
        1
    else
        0
    end;